//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error!.
        /// </summary>
        internal static string App_Error_Head {
            get {
                return ResourceManager.GetString("App_Error_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report To Us.
        /// </summary>
        internal static string App_Error_ReportUs {
            get {
                return ResourceManager.GetString("App_Error_ReportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered a temporary error and could not complete your request. &lt;br/&gt; Please try back in few minutes. &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; If you still receive this error, please report to the system administrator..
        /// </summary>
        internal static string App_Error_Text {
            get {
                return ResourceManager.GetString("App_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btnABlack {
            get {
                return ResourceManager.GetString("btnABlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string btnABlackToolTip {
            get {
                return ResourceManager.GetString("btnABlackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btnAWhite {
            get {
                return ResourceManager.GetString("btnAWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Contrast.
        /// </summary>
        internal static string btnAWhiteToolTip {
            get {
                return ResourceManager.GetString("btnAWhiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string btnContactUs {
            get {
                return ResourceManager.GetString("btnContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string btn_Language {
            get {
                return ResourceManager.GetString("btn_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        internal static string btn_Large {
            get {
                return ResourceManager.GetString("btn_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        internal static string btn_Larger {
            get {
                return ResourceManager.GetString("btn_Larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Largest Font.
        /// </summary>
        internal static string btn_LargerToolTip {
            get {
                return ResourceManager.GetString("btn_LargerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Larger Font.
        /// </summary>
        internal static string btn_LargeToolTip {
            get {
                return ResourceManager.GetString("btn_LargeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btn_Medium {
            get {
                return ResourceManager.GetString("btn_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Medium Font.
        /// </summary>
        internal static string btn_MediumToolTip {
            get {
                return ResourceManager.GetString("btn_MediumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        internal static string btn_Small {
            get {
                return ResourceManager.GetString("btn_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        internal static string btn_Smallest {
            get {
                return ResourceManager.GetString("btn_Smallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Smallest Font.
        /// </summary>
        internal static string btn_SmallestToolTip {
            get {
                return ResourceManager.GetString("btn_SmallestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Smaller Font.
        /// </summary>
        internal static string btn_SmallToolTip {
            get {
                return ResourceManager.GetString("btn_SmallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurangabad , IN.
        /// </summary>
        internal static string CityAurangabad {
            get {
                return ResourceManager.GetString("CityAurangabad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mecca, SA.
        /// </summary>
        internal static string CityMecca {
            get {
                return ResourceManager.GetString("CityMecca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medina, SA.
        /// </summary>
        internal static string CityMedina {
            get {
                return ResourceManager.GetString("CityMedina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumbai, IN.
        /// </summary>
        internal static string CityMumbai {
            get {
                return ResourceManager.GetString("CityMumbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagpur, IN.
        /// </summary>
        internal static string CityNagpur {
            get {
                return ResourceManager.GetString("CityNagpur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 10 Digit Voting Card for Address Proof..
        /// </summary>
        internal static string Error10DigitVoterAddress {
            get {
                return ResourceManager.GetString("Error10DigitVoterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 10 Digit Voting Card  for identity Proof..
        /// </summary>
        internal static string Error10DigitVoterID {
            get {
                return ResourceManager.GetString("Error10DigitVoterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please Enter 16 Digit Driving Licence Number for Address Proof..
        /// </summary>
        internal static string Error16DigitDLAddress {
            get {
                return ResourceManager.GetString("Error16DigitDLAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 16 Digit Driving Licence Number for ID Proof..
        /// </summary>
        internal static string Error16DigitDLID {
            get {
                return ResourceManager.GetString("Error16DigitDLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 12 Digit Aadhar Number for Address Proof..
        /// </summary>
        internal static string ErrorAadhar12digitAdd {
            get {
                return ResourceManager.GetString("ErrorAadhar12digitAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 12 Digit Aadhar Number for identity proof..
        /// </summary>
        internal static string ErrorAadhar12digitID {
            get {
                return ResourceManager.GetString("ErrorAadhar12digitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar Number for Address Proof and Identity Proof must be same..
        /// </summary>
        internal static string ErrorAadharNoSame {
            get {
                return ResourceManager.GetString("ErrorAadharNoSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Atleast one Address Proof..
        /// </summary>
        internal static string ErrorAtleastAddressProof {
            get {
                return ResourceManager.GetString("ErrorAtleastAddressProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Atleast one ID Proof..
        /// </summary>
        internal static string ErrorAtleastIDPrrof {
            get {
                return ResourceManager.GetString("ErrorAtleastIDPrrof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Bank Name..
        /// </summary>
        internal static string ErrorddlBankName {
            get {
                return ResourceManager.GetString("ErrorddlBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Branch Name..
        /// </summary>
        internal static string ErrorddlBranchname {
            get {
                return ResourceManager.GetString("ErrorddlBranchname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Business Address Type..
        /// </summary>
        internal static string ErrorddlBusinessAddType {
            get {
                return ResourceManager.GetString("ErrorddlBusinessAddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please Select Constitution..
        /// </summary>
        internal static string ErrorddlConstitution {
            get {
                return ResourceManager.GetString("ErrorddlConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select District..
        /// </summary>
        internal static string Errorddldistrict {
            get {
                return ResourceManager.GetString("Errorddldistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Account Type..
        /// </summary>
        internal static string ErrorddlExistingAccType {
            get {
                return ResourceManager.GetString("ErrorddlExistingAccType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Sex..
        /// </summary>
        internal static string ErrorddlGender {
            get {
                return ResourceManager.GetString("ErrorddlGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Line of Business Activity..
        /// </summary>
        internal static string ErrorddlLineofBusiness {
            get {
                return ResourceManager.GetString("ErrorddlLineofBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Loan Account Type..
        /// </summary>
        internal static string ErrorddlLoanAccountType {
            get {
                return ResourceManager.GetString("ErrorddlLoanAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Mudra Loan Type..
        /// </summary>
        internal static string ErrorddlLoanType {
            get {
                return ResourceManager.GetString("ErrorddlLoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Minority Category..
        /// </summary>
        internal static string ErrorddlMinority {
            get {
                return ResourceManager.GetString("ErrorddlMinority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Education Qualification..
        /// </summary>
        internal static string ErrorddlQualification {
            get {
                return ResourceManager.GetString("ErrorddlQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Residential Address Type..
        /// </summary>
        internal static string Errorddlresidenttype {
            get {
                return ResourceManager.GetString("Errorddlresidenttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Social Category..
        /// </summary>
        internal static string ErrorddlSocialCategory {
            get {
                return ResourceManager.GetString("ErrorddlSocialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Taluka..
        /// </summary>
        internal static string ErrorddlTaluka {
            get {
                return ResourceManager.GetString("ErrorddlTaluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Licence Number for Address Proof and Identity Proof must be same..
        /// </summary>
        internal static string ErrorDLNoSame {
            get {
                return ResourceManager.GetString("ErrorDLNoSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly enter data in below fields..
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Applicant Age Should be more than 18 years..
        /// </summary>
        internal static string ErrorMinorAge {
            get {
                return ResourceManager.GetString("ErrorMinorAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Applicant Age Should be not more than 125 years..
        /// </summary>
        internal static string ErrorMoreAge {
            get {
                return ResourceManager.GetString("ErrorMoreAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID and Address Proof must be same..
        /// </summary>
        internal static string ErrorOtherSame {
            get {
                return ResourceManager.GetString("ErrorOtherSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity proof and Address Proof for other category must be same..
        /// </summary>
        internal static string ErrorOtherSame1 {
            get {
                return ResourceManager.GetString("ErrorOtherSame1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Account Number..
        /// </summary>
        internal static string ErrorTxtAccountNumber {
            get {
                return ResourceManager.GetString("ErrorTxtAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Aadhar Number for Address Proof..
        /// </summary>
        internal static string ErrorTxtAddProofAadharNo {
            get {
                return ResourceManager.GetString("ErrorTxtAddProofAadharNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Driving Licence Number for Address Proof Number..
        /// </summary>
        internal static string ErrorTxtAddproofDLN {
            get {
                return ResourceManager.GetString("ErrorTxtAddproofDLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Voting Card Number for Address Proof..
        /// </summary>
        internal static string ErrorTxtAddproofVoterNo {
            get {
                return ResourceManager.GetString("ErrorTxtAddproofVoterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Age..
        /// </summary>
        internal static string ErrorTxtAge {
            get {
                return ResourceManager.GetString("ErrorTxtAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 1 Applicant Name..
        /// </summary>
        internal static string ErrorTxtApplicantName1 {
            get {
                return ResourceManager.GetString("ErrorTxtApplicantName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Bank Address.
        /// </summary>
        internal static string ErrorTxtBankAddress {
            get {
                return ResourceManager.GetString("ErrorTxtBankAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Business Address..
        /// </summary>
        internal static string ErrorTxtBusinessAddress {
            get {
                return ResourceManager.GetString("ErrorTxtBusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Captcha..
        /// </summary>
        internal static string ErrorTxtCaptcha {
            get {
                return ResourceManager.GetString("ErrorTxtCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Date of Birth..
        /// </summary>
        internal static string ErrorTxtDOB {
            get {
                return ResourceManager.GetString("ErrorTxtDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email..
        /// </summary>
        internal static string ErrorTxtEmail {
            get {
                return ResourceManager.GetString("ErrorTxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name of Bank and Branch..
        /// </summary>
        internal static string ErrorTxtExistingBankName {
            get {
                return ResourceManager.GetString("ErrorTxtExistingBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Amount of loan Taken..
        /// </summary>
        internal static string ErrorTxtExistingLoanAmount {
            get {
                return ResourceManager.GetString("ErrorTxtExistingLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Father/Husband Name..
        /// </summary>
        internal static string ErrorTxtFatherName {
            get {
                return ResourceManager.GetString("ErrorTxtFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Aadhar Number for identity proof..
        /// </summary>
        internal static string ErrorTxtIDProofAadharNo {
            get {
                return ResourceManager.GetString("ErrorTxtIDProofAadharNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Driving Licence Number for ID Proof Number..
        /// </summary>
        internal static string ErrorTxtIDproofDLN {
            get {
                return ResourceManager.GetString("ErrorTxtIDproofDLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Voting Card Number for Identity  Proof..
        /// </summary>
        internal static string ErrorTxtIDproofVoterNo {
            get {
                return ResourceManager.GetString("ErrorTxtIDproofVoterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter IFSC Code..
        /// </summary>
        internal static string ErrorTxtIFSC {
            get {
                return ResourceManager.GetString("ErrorTxtIFSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Kishore type loan  Amount should be more than 50000  and less than 5 lakh.  .
        /// </summary>
        internal static string ErrorTxtLoanKishore {
            get {
                return ResourceManager.GetString("ErrorTxtLoanKishore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Shishu Loan type Amount should be less than or equal to 50000. .
        /// </summary>
        internal static string ErrorTxtLoanShishu {
            get {
                return ResourceManager.GetString("ErrorTxtLoanShishu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Tarun type loan  Amount should be more than 5 lakh and less than or equal to 10 lakh..
        /// </summary>
        internal static string ErrorTxtLoanTarun {
            get {
                return ResourceManager.GetString("ErrorTxtLoanTarun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Mobile Number..
        /// </summary>
        internal static string ErrorTxtMobile {
            get {
                return ResourceManager.GetString("ErrorTxtMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Loan Amount..
        /// </summary>
        internal static string ErrortxtNubmer {
            get {
                return ResourceManager.GetString("ErrortxtNubmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Period..
        /// </summary>
        internal static string ErrorTxtPeriod {
            get {
                return ResourceManager.GetString("ErrorTxtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Residential Address..
        /// </summary>
        internal static string ErrorTxtResidentialAdd {
            get {
                return ResourceManager.GetString("ErrorTxtResidentialAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Annual Sales for Existing Business..
        /// </summary>
        internal static string ErrorTxtSalesExisting {
            get {
                return ResourceManager.GetString("ErrorTxtSalesExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Annual Sales for Proposed Business..
        /// </summary>
        internal static string ErrorTxtSalesProposed {
            get {
                return ResourceManager.GetString("ErrorTxtSalesProposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Telephone Number..
        /// </summary>
        internal static string ErrorTxtTelephone {
            get {
                return ResourceManager.GetString("ErrorTxtTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Account Number..
        /// </summary>
        internal static string ErrorValidAccount {
            get {
                return ResourceManager.GetString("ErrorValidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Captcha..
        /// </summary>
        internal static string ErrorValidCaptcha {
            get {
                return ResourceManager.GetString("ErrorValidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email Id..
        /// </summary>
        internal static string ErrorValidEmail {
            get {
                return ResourceManager.GetString("ErrorValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid 10 digit Mobile Numer. Mobile Number should be start with 7 or 8 or 9..
        /// </summary>
        internal static string ErrorValidMobile {
            get {
                return ResourceManager.GetString("ErrorValidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Number for Address Proof and Identity Proof must be same..
        /// </summary>
        internal static string ErrorVoterNoSame {
            get {
                return ResourceManager.GetString("ErrorVoterNoSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Person.
        /// </summary>
        internal static string heading {
            get {
                return ResourceManager.GetString("heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string HeadLoginStatus {
            get {
                return ResourceManager.GetString("HeadLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001/Home&apos;&gt;Home.
        /// </summary>
        internal static string HomepagePath {
            get {
                return ResourceManager.GetString("HomepagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string HyperLink1 {
            get {
                return ResourceManager.GetString("HyperLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Information Technology Corporation Limited..
        /// </summary>
        internal static string imgMahaIT_alt {
            get {
                return ResourceManager.GetString("imgMahaIT_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Account Type.
        /// </summary>
        internal static string lblAccountLoanType {
            get {
                return ResourceManager.GetString("lblAccountLoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string lblAccountNumber {
            get {
                return ResourceManager.GetString("lblAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Proof.
        /// </summary>
        internal static string lblAddproof {
            get {
                return ResourceManager.GetString("lblAddproof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar No..
        /// </summary>
        internal static string lblAdharNo {
            get {
                return ResourceManager.GetString("lblAdharNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string lblAge {
            get {
                return ResourceManager.GetString("lblAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string lblAlbum {
            get {
                return ResourceManager.GetString("lblAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Others.
        /// </summary>
        internal static string lblAnyother {
            get {
                return ResourceManager.GetString("lblAnyother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Applicant Details.
        /// </summary>
        internal static string lblApplicantName {
            get {
                return ResourceManager.GetString("lblApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Loan Details.
        /// </summary>
        internal static string lblApplicationHeading {
            get {
                return ResourceManager.GetString("lblApplicationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Applicant Name.
        /// </summary>
        internal static string lblAppName1 {
            get {
                return ResourceManager.GetString("lblAppName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Applicant Name.
        /// </summary>
        internal static string lblAppName2 {
            get {
                return ResourceManager.GetString("lblAppName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Address.
        /// </summary>
        internal static string lblBankAdd {
            get {
                return ResourceManager.GetString("lblBankAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Bank Details.
        /// </summary>
        internal static string lblBankDetails {
            get {
                return ResourceManager.GetString("lblBankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank IFSC Code.
        /// </summary>
        internal static string lblBankIFSC {
            get {
                return ResourceManager.GetString("lblBankIFSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string lblBankName {
            get {
                return ResourceManager.GetString("lblBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string lblBranch {
            get {
                return ResourceManager.GetString("lblBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Business Details.
        /// </summary>
        internal static string lblBusiness {
            get {
                return ResourceManager.GetString("lblBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Business Activity.
        /// </summary>
        internal static string lblBusinessActivity {
            get {
                return ResourceManager.GetString("lblBusinessActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Address.
        /// </summary>
        internal static string lblBusinessAddress {
            get {
                return ResourceManager.GetString("lblBusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        internal static string lblBusinessAddType {
            get {
                return ResourceManager.GetString("lblBusinessAddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        internal static string Lblcaptcha {
            get {
                return ResourceManager.GetString("Lblcaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Captcha.
        /// </summary>
        internal static string lblcaptchaText {
            get {
                return ResourceManager.GetString("lblcaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        internal static string lblConstitution {
            get {
                return ResourceManager.GetString("lblConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra State Pradhan Mantri Mudra Yojana , Government of Maharashtra.
        /// </summary>
        internal static string lbldepName {
            get {
                return ResourceManager.GetString("lbldepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © This is the official website of planning department. All rights reserved | Developed by.
        /// </summary>
        internal static string lblDevelopedby {
            get {
                return ResourceManager.GetString("lblDevelopedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string lblDistrict {
            get {
                return ResourceManager.GetString("lblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictContact {
            get {
                return ResourceManager.GetString("LblDistrictContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL No.
        /// </summary>
        internal static string lblDLNo {
            get {
                return ResourceManager.GetString("lblDLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string lblDOB {
            get {
                return ResourceManager.GetString("lblDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPO Name.
        /// </summary>
        internal static string LblDponame {
            get {
                return ResourceManager.GetString("LblDponame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        internal static string lblEmailId {
            get {
                return ResourceManager.GetString("lblEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        internal static string LblEmailIdContact {
            get {
                return ResourceManager.GetString("LblEmailIdContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of Existing Accounts ,if any.
        /// </summary>
        internal static string LblExistingAcc {
            get {
                return ResourceManager.GetString("LblExistingAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string lblExistingAccType {
            get {
                return ResourceManager.GetString("lblExistingAccType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Bank &amp; Branch.
        /// </summary>
        internal static string LblExistingBank {
            get {
                return ResourceManager.GetString("LblExistingBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Loan A/c, amount of loan taken.
        /// </summary>
        internal static string LblExistingLoanAmount {
            get {
                return ResourceManager.GetString("LblExistingLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience, if any.
        /// </summary>
        internal static string lblExperience {
            get {
                return ResourceManager.GetString("lblExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father/Husband Name.
        /// </summary>
        internal static string lblFather {
            get {
                return ResourceManager.GetString("lblFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your Financer.
        /// </summary>
        internal static string lblfinancer {
            get {
                return ResourceManager.GetString("lblfinancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string lblGallery {
            get {
                return ResourceManager.GetString("lblGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Proof.
        /// </summary>
        internal static string lblIDproof {
            get {
                return ResourceManager.GetString("lblIDproof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Search.
        /// </summary>
        internal static string lblKeywordsearch {
            get {
                return ResourceManager.GetString("lblKeywordsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KISHOR.
        /// </summary>
        internal static string lblKishor {
            get {
                return ResourceManager.GetString("lblKishor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYC Documents.
        /// </summary>
        internal static string lblKYC {
            get {
                return ResourceManager.GetString("lblKYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. KYC Documents.
        /// </summary>
        internal static string lblKycHeading {
            get {
                return ResourceManager.GetString("lblKycHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Business Activity (Purpose).
        /// </summary>
        internal static string lblLineofBusiness {
            get {
                return ResourceManager.GetString("lblLineofBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Loan Details.
        /// </summary>
        internal static string LblLoan {
            get {
                return ResourceManager.GetString("LblLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudra Loan Type.
        /// </summary>
        internal static string lblLoanType {
            get {
                return ResourceManager.GetString("lblLoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Minority.
        /// </summary>
        internal static string lblminority {
            get {
                return ResourceManager.GetString("lblminority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string lblMobile {
            get {
                return ResourceManager.GetString("lblMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string lblMobileNumber {
            get {
                return ResourceManager.GetString("lblMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivational.
        /// </summary>
        internal static string lblMotivational {
            get {
                return ResourceManager.GetString("lblMotivational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        internal static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;~/Site/Home/NewsMore.aspx&apos;&gt;Read More&lt;/a&gt;.
        /// </summary>
        internal static string lblNewsMore {
            get {
                return ResourceManager.GetString("lblNewsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for new user registration.
        /// </summary>
        internal static string lblNewUserRegister {
            get {
                return ResourceManager.GetString("lblNewUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive (e.g. A-a).
        /// </summary>
        internal static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address.
        /// </summary>
        internal static string LblOfficeAddress {
            get {
                return ResourceManager.GetString("LblOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string lblperiod {
            get {
                return ResourceManager.GetString("lblperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string lblPhoto {
            get {
                return ResourceManager.GetString("lblPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Qualification.
        /// </summary>
        internal static string lblQualification {
            get {
                return ResourceManager.GetString("lblQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Address.
        /// </summary>
        internal static string lblResidentialAddress {
            get {
                return ResourceManager.GetString("lblResidentialAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        internal static string lblResidenttype {
            get {
                return ResourceManager.GetString("lblResidenttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Reviewed:.
        /// </summary>
        internal static string lblReviewDate {
            get {
                return ResourceManager.GetString("lblReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales for Existing (Rs. in Lakh).
        /// </summary>
        internal static string lblSalesExisting {
            get {
                return ResourceManager.GetString("lblSalesExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales for Proposed (Rs. in Lakh).
        /// </summary>
        internal static string lblSalesProposed {
            get {
                return ResourceManager.GetString("lblSalesProposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearchBTN {
            get {
                return ResourceManager.GetString("lblSearchBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are searching for this word :.
        /// </summary>
        internal static string lblSearchword {
            get {
                return ResourceManager.GetString("lblSearchword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string lblsex {
            get {
                return ResourceManager.GetString("lblsex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHISHU.
        /// </summary>
        internal static string lblShisu {
            get {
                return ResourceManager.GetString("lblShisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string lblsitemap {
            get {
                return ResourceManager.GetString("lblsitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Category.
        /// </summary>
        internal static string lblSocialCategory {
            get {
                return ResourceManager.GetString("lblSocialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrNo.
        /// </summary>
        internal static string LblSrno {
            get {
                return ResourceManager.GetString("LblSrno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Start Date :.
        /// </summary>
        internal static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        internal static string lblSuccessStories {
            get {
                return ResourceManager.GetString("lblSuccessStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taluka.
        /// </summary>
        internal static string lblTaluka {
            get {
                return ResourceManager.GetString("lblTaluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARUN.
        /// </summary>
        internal static string lblTarun {
            get {
                return ResourceManager.GetString("lblTarun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No.
        /// </summary>
        internal static string lblTelephone {
            get {
                return ResourceManager.GetString("lblTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.No..
        /// </summary>
        internal static string LblTelNo {
            get {
                return ResourceManager.GetString("LblTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Count:.
        /// </summary>
        internal static string lblTodaysVisitor {
            get {
                return ResourceManager.GetString("lblTodaysVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors :.
        /// </summary>
        internal static string lblTotalVisitor {
            get {
                return ResourceManager.GetString("lblTotalVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Site.
        /// </summary>
        internal static string lblViewPartnersHeading {
            get {
                return ResourceManager.GetString("lblViewPartnersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter ID No..
        /// </summary>
        internal static string lblVoterId {
            get {
                return ResourceManager.GetString("lblVoterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © This is the official website of Planning Department, Government of Maharashtra. All Rights Reserved..
        /// </summary>
        internal static string lbl_copyright {
            get {
                return ResourceManager.GetString("lbl_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pradhan Mantri Mudra Yojana &lt;br/&gt;&lt;span&gt;Government of Maharashtra&lt;/span&gt;.
        /// </summary>
        internal static string lbl_headTitle {
            get {
                return ResourceManager.GetString("lbl_headTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Content.
        /// </summary>
        internal static string lbl_skipToContent {
            get {
                return ResourceManager.GetString("lbl_skipToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Navigation.
        /// </summary>
        internal static string lbl_skipToNav {
            get {
                return ResourceManager.GetString("lbl_skipToNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of India.
        /// </summary>
        internal static string NationalEmblem_alt {
            get {
                return ResourceManager.GetString("NationalEmblem_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        internal static string searchTxtBox {
            get {
                return ResourceManager.GetString("searchTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_btn {
            get {
                return ResourceManager.GetString("Search_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here :.
        /// </summary>
        internal static string SitemapMsg {
            get {
                return ResourceManager.GetString("SitemapMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for visiting Pradhan Mantri Mudra Yojana Maharashtra State Website..
        /// </summary>
        internal static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
